Repository cisagov/domain-manager-api, pull requests merged in 2021-05, with the labels that each got.

#219 Fix user guide download endpoint
  src/api/views/help_views.py
Labels: bugfix

#220 DM-403 Remove requester_name from model
  src/api/schemas/application_schema.py
  src/scripts/data/applications.json
  tests/data/application_data.py
Labels: enhancement

#227 switch www CNAME record to A record
  src/utils/aws/__init__.py
  src/utils/aws/record_handler.py
  src/utils/aws/site_handler.py
Labels: bug

#233 User confirmed email
  src/api/main.py
  src/api/schemas/user_shema.py
  src/api/templates/emails/new_user_registered.html
  src/api/templates/emails/user_confirmed.html
  src/api/views/application_views.py
  src/api/views/auth_views.py
  src/api/views/user_views.py
  src/utils/aws/cognito.py
  src/utils/decorators/__init__.py
  src/utils/notifications.py
Labels: enhancement

#232 CPD-124 Create Domain Error Responses
  src/api/views/domain_views.py
  src/settings/__init__.py
  src/utils/aws/record_handler.py
  src/utils/aws/site_handler.py
  src/utils/notifications.py
  src/utils/validator.py
Labels: enhancement

#234 Log SES Errors
  src/utils/notifications.py
Labels: enhancement

#235 STS Expire Token Bug
  src/api/main.py
  src/api/views/auth_views.py
  src/api/views/domain_views.py
  src/api/views/email_address_views.py
  src/api/views/user_views.py
  src/scripts/data/applications.json
  src/scripts/initialize.py
  src/utils/aws/clients.py
  src/utils/aws/cognito.py
  src/utils/aws/s3.py
  src/utils/aws/ses.py
  src/utils/aws/sts.py
  src/utils/notifications.py
Labels: bug
